### ISSUE TITLE
fontsUrl is ignored

### ISSUE THREAD

**Issue by virgilbugnariu** [tancredi/fantasticon#1]
Hey. Great job rewriting this. Already fixed some issues I've been having trouble with. 

I am using a .fantasticonrc.js file to pass the config. Looks like there is an issue with the `fontsUrl` property. It seems to be ignored completely and does not change the resulted URL from the .css file. Looking at the `renderSrcAttribute` function it looks like it should do the job.

**Comment by tancredi** [comment]
Addressed in `1.0.8`. Thanks :)
