### ISSUE TITLE
Feature Request: Vertically center the symbols inside the font.

### ISSUE THREAD

**Issue by tec-lab** [tancredi/fantasticon#13]
Comparing with Fontawesome https://fontawesome.com/icons?d=gallery all symbols are vertically centered. This is necessary when a symbol is not using the whole height while others do. In the case of fantasticon all symbols are bottom aligned, this makes it impossible to align the symbol with others next-to-next vertically centered.

The -n (normalize) unfort. is not a solution since it also scales line width of symbol.
Would be great to have an option to vertically center the symbols inside the font.

thx

**Comment by tancredi** [comment]
Hi @tec-lab - while vertical alignment seems to be a tad unpredictable, you can use the `descent` option to adjust it manually - may be a bit tedious but once you picked the right value you won't have to worry about it anymore

Hope this helps, let me know if it fixes it for you

**Comment by tec-lab** [comment]
Hi, I already played with the descent option but have seen no effect at all. Finally I added a frame around every symbol so that all gets centered vertically. Not sure exactly how SVG handles this, either the frame is 100% transparent or it defines a kind of page size where the symbol is drawn. Anyhow the frame is not visible in font.

Thx for your support. This issue can be closed.

**Comment by harun911** [comment]
@teclab-at Do you care to explain how you solved this issue?

**Comment by harun911** [comment]
Thanks you so much for your reply!
