### ISSUE TITLE
Fill color from the svg icons is not included in the generator font.

### ISSUE THREAD

**Issue by lillallol** [tancredi/fantasticon#133]
So I am trying to generate a font from these two svg icons : [1](https://raw.githubusercontent.com/microsoft/vscode-icons/afa041d46f4323acdad167afdded418db08cd1da/icons/dark/symbol-variable.svg),[2](https://raw.githubusercontent.com/microsoft/vscode-icons/main/icons/dark/symbol-class.svg) (look top left for the icon in the links).

Using fantasticon, the generated font does not have the original color. I took a look at the README.md file and could not find something of help.

I have tried generating the font using [icomoon](https://icomoon.io/app/#/select) and the color is preserved via css property color.

How can I do that with fantasticon?

**Comment by cclp94** [comment]
I am also interested in this feature! I have been looking for a cli solution that I could run in a CI pipeline and so far no luck. The workaround right now is use iconmoon or add the colors yourself in the CSS.

**Comment by tancredi** [comment]
Hi @lillallol - color information is not related to font generation - `icomoon` provides an option to generate that into the default CSS  for an icon, which is a kind of feature I may decide to support in the future but so far doesn't seem core to the library.

For now, you can simply add CSS styling to your icons manually.

**Comment by lillallol** [comment]
@tancredi Thanks for the answer. Feel free to close the issue if you want or let it be a feature request.

**Comment by oneezy** [comment]
hey guys, i also need this feature.

**Comment by rnuravtsev** [comment]
Hello, we need this feature
