### ISSUE TITLE
Multiple tag name would be awesome

### ISSUE THREAD

**Issue by alexandreDavid** [tancredi/fantasticon#146]
I'm using a lib which includes my icons by a prop name (Vue.js + Primevue).
The problem is this lib uses span for the icons element.
It might be good if I can define an array of possible elements instead of a tag in string.
I tried with selector but didn't work because of ' escape.

**Comment by tancredi** [comment]
They use `i` by default - you can specify a different tag with the `tag` options - e.g. `fantasticon --tag div` using the cli or `tag: 'div'` using a config file
