### ISSUE TITLE
SVG Font-Type duplicate icon with fileName as unicode

### ISSUE THREAD

**Issue by dobbidev** [tancredi/fantasticon#154]
Hello,

The SVG Font-Type generates a duplication of one icon:
![image](https://user-images.githubusercontent.com/12251432/111604799-f4d02e80-87d5-11eb-82f2-a409d46c4613.png)
The first is the normal (expected) icon, the second has the glyph-name as unicode name. 

The old package icon-font-generator was not doing something like this.

I think the position of this behavior is here:
https://github.com/tancredi/fantasticon/blob/01e20ad37e8796c5b12984011577075cf72571d1/src/generators/asset-types/svg.ts#L40

**Problem**
The svg file gets very big: 2-3x bigger then normal.

Is that wanted? When yes, is there a solution provided where i can deactivate this behavior? 

Thanks

Dobbi

**Comment by tancredi** [comment]
Hi @dobbidev - merged a PR that should address this - please let me know if there's any issues with it

**Comment by tancredi** [comment]
(fix available in `v1.2.2`)
