### ISSUE TITLE
Invisible elements end up in font

### ISSUE THREAD

**Issue by brunnerh** [tancredi/fantasticon#164]
If you have something like guide shapes or "source" elements in your SVG file that are hidden, they still appear in the font.

E.g. a hidden layer created in Inkscape will create Elements like this:

```svg
<g
     inkscape:label="Guides"
     inkscape:groupmode="layer"
     id="layer1"
     sodipodi:insensitive="true"
     style="display:none">
    ....
</g>
```

So I suppose elements with `display` = `none` should be filtered out.

**Comment by brunnerh** [comment]
As a workaround I currently pre-process the icons via SVGO which removes these elements.

**Comment by tancredi** [comment]
Yes, all paths will be turned into solid filling, so anything hidden / not flattened should be removed.

I'm thinking to pipe all SVGs through SVGO automatically in the future, for the time being SVGs just need to be clean :)
