### ISSUE TITLE
Use handlebars helpers?

### ISSUE THREAD

**Issue by danielbaars** [tancredi/fantasticon#175]
Is it possible to use handlebar helpers and if so: how?

**Comment by nemaanshul** [comment]
You can register helpers using 
https://www.npmjs.com/package/express-handlebars

**Comment by ranjan-purbey** [comment]
Yes, you can use handlebars helpers. First you need to register your helpers in fantasticon config file (fantasticonrc.js). Then those helpers will be available in your hbs templates
