### ISSUE TITLE
Introduce CI test workflow

### ISSUE THREAD

**Issue by casaper** [tancredi/fantasticon#19]
The project seems to have decent tests, but they don't appear to be verifying Pull requests.

**Comment by tancredi** [comment]
HI @casaper - they do on my branches with GitHub Actions - I would have expected to do the same on forked branches. As soon as I have a minute I'll look at your PR and also figure this out.

By the way, thank you so much for contributing! Could only take a brief look so far, but looks a solid amount and quality of work :)

**Comment by casaper** [comment]
Hi @tancredi 

> they do on my branches with GitHub Actions

Strange, that they didn't run on my PR's.

> By the way, thank you so much for contributing! Could only take a brief look so far, but looks a solid amount and quality of work :)

No worries... I actually had the peersonal/business need, but then got carried away a bit.. ;) 
I just noticed that someone else also implemented templates... two PR's doing the same thing but different. 

But having a glance at #20 I think it would probably be best to merge his first, and then I'll fidle #18   to fit into the result again.

At first glance @janbiasi  seems to have done indented Sass as well which I didn't. Mine has a bit more extensive features regarding the scss. Plus #17 is actually also in #18 included.

**Comment by tancredi** [comment]
@casaper CI now runs on PRs from forks - gonna be a bit messy as I made other changes (OS matrix) that messes up currently as we have previous set of actions cached, but that should go away with new PRs.
