### ISSUE TITLE
Make JSON Template available

### ISSUE THREAD

**Issue by eWert-Online** [tancredi/fantasticon#29]
For our use-case it would be really cool, if we could change the output format of the generated json file.
I saw that there are already template options available for css, html, sass and scss, but not for json. 

Is that because of the hbs template parsing?

(Great work on the library btw 🙂 )

**Comment by casaper** [comment]
There is a format option where you can set the indent spaces of the JSON. 

Other than that I'd not really see any point in such thing. Or what would you want to achieve by that?

**Comment by eWert-Online** [comment]
We are using the Patternlab (https://patternlab.io/) for one of our clients. 
In there you specify the data for your pattern in json. Which in this case would be all available icon names.
Right now everything but the json does get auto generated. Which is pretty cool. It would be even better, if the json could also be auto-generated, so if we add an icon, the whole "documentation" will get updated automatically.
Right now we would have to remember, to update the json as well.

I mean currently I don't really see for which use-case I would need the generated json. 
If we could specify any arbitrary schema though, you could do lots of things with it.

For us for example it would need to be in the following format:

```json
{
    "icons": [
        {
            "name": "bars"
        },
        {
            "name": "checkmark-circle"
        },
        {
            "name": "checkmark-square"
        },
        ...
    ]
}
```

**Comment by casaper** [comment]
But if you want to customize that far, I would anyway create a script to run fantasticon. I do that as well in the project I use fantasticon for. 

It will return [RunnerResults](https://github.com/tancredi/fantasticon/blob/master/src/core/runner.ts#L15) and from there you can build virtually any json or other format you desire much better than with a template.

**Comment by casaper** [comment]
Or perhaps that is a think. I'll have a look at paternlab when I'll get arround to do so. I'm too busy at the moment. But the actual intiator @tancredi might have an idea too

**Comment by eWert-Online** [comment]
Thats a really good suggestion. 
I didn't think about the fact, that i also could use this as a library in a node script. I am now using this to generate the josn in my desired format.
Thank you!

**Comment by casaper** [comment]
@eWert-Online 

I use ts-node btw, since I can make my script in typescript then.

And I also have done a workflow for this. The Icon set is before it is passed through fantasticon optimized with svgo.

**Comment by tancredi** [comment]
Hey there - yes, I'd say if you need to do more to the json you can do that before / after - using the API but also using the output JSON itself.

E.g. you could still run it as npm script and have a post-process script: `fantasticon && npm run generate-docs` and use the output JSON in the second script.

An idea I'd be more inclined to implement would be to have an option for transform scripts that act on the various asset types output, but for now it seems like anything outside the core functionality would need a solid use case to be in consideration, make sense?
