### ISSUE TITLE
[Question] Did you plan to support svg line icon ?

### ISSUE THREAD

**Issue by laurent-d** [tancredi/fantasticon#294]
Hi thanks for this great work !!!

I tried to convert svg icon composed only by line.
The result is not as excepted.
<img width="777" alt="Capture d’écran 2021-10-13 à 18 50 09" src="https://user-images.githubusercontent.com/6553086/137178056-fdbdc3a2-0875-472e-b6a1-911cd7e3ffbb.png">
Will you plan to add an option to this type of svg ?

**Comment by riheldo** [comment]
@laurent-d i have the same problem.
I use https://github.com/oslllo/svg-fixer to fix the svgs

**Comment by laurent-d** [comment]
Thanks a lot @riheldo ! I use a workaround in using inkscape scripted but this package its 10x better than install inscape and do the job..
