### ISSUE TITLE
[Question] What is the use of the codepoints parameter?

### ISSUE THREAD

**Issue by jimmyandrade** [tancredi/fantasticon#3]
I wish I could define codepoints for each glyph. Is it possible to do this through the `codepoints` parameter?

**Comment by tancredi** [comment]
Yes, you can pass a map of codepoint values for each asset slug. You'll have to use a config file or the JS API as the option is not available from the cli. Ones you don't specify will be automatically filled. Let me know if you have any issues.

**Comment by jimmyandrade** [comment]
@tancredi Thank you for the quick response.

Currently, in the documentation, are there any examples of how this can be done?
By the way, I believe I could contribute to the project 😄

**Comment by tancredi** [comment]
Multiple codepoints are not supported - of course it wouldn't be major to implement (may I ask for what use case though?)

Yes, the docs are still very rough, as you can see so far I've only pasted a few examples but nothing major. I'll put some more time on it soon, there's plenty more if like to do, but I just wanted to prevent more bleeding of issues and unmerged PRs on the previous codebase, so I published this a bit rough around he edges.

If you wanna contribute, that would be great. Let me know beforehand what you'd be thinking about doing, and I'd be happy to help!
