### ISSUE TITLE
Do not to use the method "join" from the path for generating font path in CSS template

### ISSUE THREAD

**Issue by Vadimator** [tancredi/fantasticon#30]
Is it possible do not to use the method "join" from the path for generating font path in CSS template?

![image](https://user-images.githubusercontent.com/14293024/99954036-6d703280-2d82-11eb-8e16-06540969f636.png)

I have different directories for fonts and styles and I need to combine them. I use fontsUrl parameter in the config, but in the windows environment, the method "join" changes slash in the path...

Config:
![image](https://user-images.githubusercontent.com/14293024/99954683-71e91b00-2d83-11eb-99cf-d3601457bb99.png)

Receive:
![image](https://user-images.githubusercontent.com/14293024/99954772-8f1de980-2d83-11eb-858e-98b0db17c967.png)

Expect:
I would like to use a forward slash in the font path.
![image](https://user-images.githubusercontent.com/14293024/99954865-b2e12f80-2d83-11eb-87c3-a8b9edf5faf0.png)

**Comment by casaper** [comment]
I also had some changes there in mind. IE return an array with each formats url line, and not having it joined, so that could be done in the .hbs templates. Would make more sense. :thumbsup:

**Comment by tancredi** [comment]
Fixed in `1.0.21`
