### ISSUE TITLE
fontUrl: path.join() does not work well with URL's

### ISSUE THREAD

**Issue by voltane** [tancredi/fantasticon#32]
Hi!
I found that when `fontUrl` is directly set as an URL (in my case S3 bucket) then CSS font has one slash truncated due to how path.join() works.

For example:
`https://my-statics.example.com/icons` is rendered in CSS file as `https:/my-statics.example.com/icons`.

Relevant line:
https://github.com/tancredi/fantasticon/blob/4e706c16aa5a6887368a96931c19359c5fa12cc6/src/utils/css.ts#L34

I know that it was probably designed to work with directory path's (like `/static/icons`) but i think it is considerable to make it work with valid URL addresses.

**Comment by tancredi** [comment]
Fixed in `1.0.21`
