### ISSUE TITLE
A `nameTransformer` config would be nice

### ISSUE THREAD

**Issue by raystubbs** [tancredi/fantasticon#35]
Current API doesn't allow much control over how the class names are build.  Some kind of name transformer function passed in the config to give users control over this would be helpful; with a reasonable default to replace special characters from the file names.

**Comment by casaper** [comment]
The class names can be fully customized by using custom templates for what ever style sheet output you use.

You can use the default templates fantasticon uses as a starting point:

- https://github.com/tancredi/fantasticon/blob/master/templates/css.hbs
- https://github.com/tancredi/fantasticon/blob/master/templates/sass.hbs
- https://github.com/tancredi/fantasticon/blob/master/templates/scss.hbs

And then you can pass your custom templates path with the config like in the readme example:

```js
module.exports = {
  // ...
  templates: { css: './my-custom-tp.css.hbs' },
  // ...
}
```
