### ISSUE TITLE
html render a black rectangle

### ISSUE THREAD

**Issue by golayp** [tancredi/fantasticon#368]
Hi,
I'm facing a strang issue. When generating icons font and testing it with the index.html file, there is a black rectangle above my icons that cannot be removed. 
This black box can't be inpected with the web debbugger since there is no element in the dom corresponding to that box.
![Capture](https://user-images.githubusercontent.com/29345/158393376-446ce432-698c-48ec-98e7-2d63e4dd3f17.PNG)
Is there someone with same issue ?

Thank for your help.

**Comment by ndrohith09** [comment]
No , for me everything seems to be perfect but my icon size is too small. I dont get how to resize my icon size.

**Comment by oskameDEV** [comment]
In my use and getting the black fills in the wrong places the SVG vector needed to be flat.

So no paths ([Object → Path → Outline Stroke] for any paths without a fill that exist)
And possibly no clipping or compounds too, I had one shape that had one surrounding it had to remove.

**Comment by polonmedia** [comment]
@golayp Did u resolve it somehow?

**Comment by golayp** [comment]
> @golayp Did u resolve it somehow?
> 
> nvm, SVGs need to be non figma or other software induced

Oh yes @polonmedia , I have cleaned my svg in order to avoid this issue.
