### ISSUE TITLE
[Nice to have] TS Interface ESLint rules

### ISSUE THREAD

**Issue by virgilbugnariu** [tancredi/fantasticon#5]
The generated interface does not comply with the eslint rules we're using in our project (in our case, using double quotes instead of single quotes). For now running eslint with the --fix argument does the trick, but it would be nice to have the possibility of customising the way the interface is generated.

**Comment by tancredi** [comment]
Hi @virgilbugnariu - I think too much depends on which tool one uses in their codebase - for example, in most of my TS projects all of my auto-fixing is done by Prettier, so I would feed the generated types through prettier-cli right after the generation.

I think it would be too much for this tool to be aware of formatting rules for whatever platform users are adopting.

I think it's best to leave this to steps post-generation, what do you think?

**Comment by virgilbugnariu** [comment]
Fair enough. 
Wasn't really sure how such a thing would've worked out, but I though it was worth opening up a discussion about it.

Thanks 👍
