### ISSUE TITLE
Only works with a few svg files

### ISSUE THREAD

**Issue by kaumac** [tancredi/fantasticon#57]
We've been using this library heavily and it saves us a lot of development time, but at the same time it costs a lot of time for designers.
We use Figma for everything, but this library only works for svg files exported from Illustrator, if we export from anywhere else it doesn't work.

Any ideas what we are doing wrong? Is it supposed to only work with illustrator svgs?

This is how the html preview looks like when exported straight from Figma:

<img width="1680" alt="Screen Shot 2020-12-14 at 09 30 32" src="https://user-images.githubusercontent.com/1170740/102081839-a6368100-3def-11eb-9aaf-d077c96f3311.png">

And this is is how it looks like when exported from Illustrator:

<img width="1679" alt="Screen Shot 2020-12-14 at 09 34 04" src="https://user-images.githubusercontent.com/1170740/102081886-b9e1e780-3def-11eb-8482-6374208803eb.png">

These are some of the svg that does not work
[from figma not working.zip](https://github.com/tancredi/fantasticon/files/5688777/from.figma.not.working.zip)

These are some of the svg that works:
[from-illustrator-working.zip](https://github.com/tancredi/fantasticon/files/5688782/from-illustrator-working.zip)

**Comment by tancredi** [comment]
Hi @kaumac there's absolutely no software requirement here as long as vectors are flattened and valid.

The not working folder SVGs are mostly empty files (see attachments :) )

(That said, I love Figma but not sure it would be my tool of choice for the icons design, as it's just not what it does best)

<img width="436" alt="Screenshot 2020-12-14 at 10 24 29" src="https://user-images.githubusercontent.com/1300753/102070481-1563a380-3df7-11eb-809c-14c4ce40a33e.png">

**Comment by kaumac** [comment]
Thanks a lot for the very quick response @tancredi !

My bad, I've used the wrong files. I've updated the issue description, do you mind having another look?

Regarding their reasoning behind Figma, I think it's because they only use Illustrator to create the icons, but use Figma for documentation and handoff of the design for developers.

So the workflow we're trying to achieve is: Designers give a figma file/link with a new page design to be implemented which contains the icons. Then the developer exports the icon as svg and drops it into the icons folder, which is then converted and available to use.

**Comment by kaumac** [comment]
@tancredi the designers tried flattening the svgs and that did the trick! 🎉

Thanks a lot for the help, I'll close the issue

**Comment by kaumac** [comment]
PS: It would be nice to have the SVG format/requirements documented in the documentation 😄
