### ISSUE TITLE
Usage of codepoints

### ISSUE THREAD

**Issue by mw-muwo** [tancredi/fantasticon#59]
Hey @tancredi could you please tell me how to use the codepoints in a config file? 

if you could show me a simple example i'd create a PR for the "official" documentation in your readme.

Best regards

**Comment by casaper** [comment]
@mw-muwo 

The codepoints would pre reserve a certain set of codepoint values you'd want the font generator to skip over AFAIS.

It normally starts with `\f101` and increments from there onwards to assign the icon svgs you feed into fantasticon. In my use case that is:

```scss
$icons-map: (
  'first-icon': '\f101',
  'second-icon': '\f102',
  // ...
  'world': '\f288',
  'xing': '\f289'
)
```

If I passed in:

```ts
config = {
  codepoints: {
    'xyz-icon': 0x101,
    'abc-icon' 0x102
  }
}
```

These two will be skipped over, so:

```scss
$icons-map: (
  'first-icon': '\f103',
  'second-icon': '\f104',
  // ...
  'world': '\f289',
  'xing': '\f290'
)
```

What the whole point in this is, is for me personally a mistery, but thats basically the effect of using this option.

**Comment by tancredi** [comment]
I guess people can use this to lock codepoints and avoid updates to the font overriding one icon with the other. I'm not personally bothered with it most of the time but some use cases are more needy than others.

Thanks @casaper for answering in detail :)

**Comment by mw-muwo** [comment]
@casaper this works perfectly, thanks for your support ❤️

**Comment by deepak311997** [comment]
Hi, is there a way to use the json generated for successive new svg addition to persist the unicode just like codepoints instead of json object can i give a json file ?
