### ISSUE TITLE
File names with "_" are getting stripped off

### ISSUE THREAD

**Issue by rahulbvnera** [tancredi/fantasticon#6]
If the file name has "_" in the name, the generated icons in the asset files are striping it out.

```
fantasticonrc.js

module.exports = {
  inputDir: "<>",
  outputDir: "<>",
  fontTypes: ["woff2"],
  assetTypes: ["css", "json", "html"],
  fontsUrl: "./",
  prefix: "<>",
  name: "<>,
  normalize: true,
};
```

**icon file name:** icon_flag.svg

json file generated: 
```
{
    iconflag: 61697
}
```

css:
```
    iconflag:before {
      content: "\f101";
    }
```

**Comment by tancredi** [comment]
Thanks @rahulbvnera - just published https://github.com/tancredi/fantasticon/releases/tag/1.0.11 - should be addressed now - please confirm 👍

**Comment by rahulbvnera** [comment]
Thank you so much for the prompt response and the fix @tancredi ! Confirmed that the latest version fixes the issue, thanks a ton!! :)
