### ISSUE TITLE
font not rending properly

### ISSUE THREAD

**Issue by yamatsum** [tancredi/fantasticon#64]
I'm trying to generate [octicons](https://github.com/primer/octicons) icon fonts using fantasticon.
When I ran it, the resulting font was filled in a strange state.

expected:
<img width="56" alt="Screen Shot 2020-12-23 at 12 38 04" src="https://user-images.githubusercontent.com/42740055/102956549-b8b16880-451b-11eb-88d6-5c65ddfdd824.png">

actual:
<img width="82" alt="Screen Shot 2020-12-23 at 12 37 05" src="https://user-images.githubusercontent.com/42740055/102956463-94558c00-451b-11eb-9674-092fe9c16d1d.png">

I tried changing the height and using svgo by referring to the following issues, but it did not solve.
Is there any solution?

https://github.com/Workshape/icon-font-generator/issues/53

**Comment by giovanni-bertoncelli** [comment]
@yamatsum how did you resolved?

**Comment by giovanni-bertoncelli** [comment]
@kabouzeid you can try this tool: https://github.com/oslllo/svg-fixer

**Comment by kabouzeid** [comment]
Thanks, I also figured this out :)

Funnily enough, I just saw that the project I needed this for is from the author of this issue, @yamatsum 😅

https://github.com/yamatsum/nonicons/pull/11

**Comment by HighSoftWare96** [comment]
Small world

**Comment by yamatsum** [comment]
I solved it using a figma plugin（https://www.figma.com/community/plugin/771155994770327940/Fill-Rule-Editor）.
However, oslllo/svg-fixer may be easier to solve, so I will verify it myself
